#!/usr/bin/env bash
# bet your you are

# Read the file line by line using while loop
while IFS=: read -r username _ userid _ _ home _; do
    # Display the required information
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $home"
    echo
done < /etc/passwd
