#!/usr/bin/env bash
# dam

# Initialize a counter variable
counter=0

# Start the while loop
while [ $counter -lt 10 ]; do
    # Increment the counter by 1
    counter=$((counter+1))

    # Display the message
    echo "Best School"
done
