#!/usr/bin/env bash
displays the time for 12 hours and 59 minutes:

#displays hours from 0 to 12
#displays minutes from 1 to 59

((hour=0))

while ((hour <= 12))
do
echo "Hour: $hour"
	((minutes=1))
	while  ((minute <= 59))
 	do
		echo "$minutes"
		((minute++))
	done
((hour++ ))
done
